### ISSUE TITLE
there is no gradient

### ISSUE THREAD

**Issue by xuridongshengpxd** [googleinterns/deep-stabilization#10]
Hi author,
good job.when  i ran the train.py,i meet this error.

File "D:\mycodeapp\anaconda\envs\py7\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\mycode\deep-stabilization-master\dvs\model.py", line 27, in forward
    self.hx, self.cx = self.LSTM(x, (self.hx, self.cx))
  File "D:\mycodeapp\anaconda\envs\py7\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\mycodeapp\anaconda\envs\py7\lib\site-packages\torch\nn\modules\rnn.py", line 974, in forward
    self.bias_ih, self.bias_hh,
 (function _print_stack)
Traceback (most recent call last):
  File "D:/mycode/deep-stabilization-master/dvs/train.py", line 276, in <module>
    train(args = args)
  File "D:/mycode/deep-stabilization-master/dvs/train.py", line 254, in train
    train_loss = run_epoch(model, train_loader, cf, count, lr, optimizer=optimizer, clip_norm=clip_norm, is_training=True, USE_CUDA=USE_CUDA)
  File "D:/mycode/deep-stabilization-master/dvs/train.py", line 147, in run_epoch
    loss.backward(retain_graph=True)
  File "D:\mycodeapp\anaconda\envs\py7\lib\site-packages\torch\tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "D:\mycodeapp\anaconda\envs\py7\lib\site-packages\torch\autograd\__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2048]] is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

**Comment by WarlockWendell** [comment]
Hi! did you find a solution to your problem？ I also had the same problem.

**Comment by zhmeishi** [comment]
It seems the problem of the Pytorch version. Please try Pytorch 1.0.0 or replace `LayerLSTM` class with `nn.LSTM`.

**Comment by WarlockWendell** [comment]
> It seems the problem of the Pytorch version. Please try Pytorch 1.0.0 or replace `LayerLSTM` class with `nn.LSTM`.

Problem solved! Thanks for your reply!

**Comment by etoilestar** [comment]
hello， could you tell me how to replace LayerLSTM with nn.LSTM

**Comment by CLoudSnowMan** [comment]
modify like this: @etoilestar 
class LayerLSTM(nn.Module):
    def __init__(self, input_size, hidden_size, bias):
        super(LayerLSTM, self).__init__()
        self.LSTM = nn.LSTMCell(input_size, hidden_size, bias)
        self.hidden_size = hidden_size
    
    def init_hidden(self, batch_size):
        self.hx = torch.zeros((batch_size, self.hidden_size)).cuda()
        self.cx = torch.zeros((batch_size, self.hidden_size)).cuda()

    def forward(self, x):
        x,_ = self.LSTM(x, (self.hx, self.cx))
        return x
